// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: template_match.proto
#ifndef GRPC_template_5fmatch_2eproto__INCLUDED
#define GRPC_template_5fmatch_2eproto__INCLUDED

#include "template_match.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

// The greeting service definition.
class ImageRecognitionRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "ImageRecognitionRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends an image to be stored
    virtual ::grpc::Status PostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::ImageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageResponse>> AsyncPostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageResponse>>(AsyncPostImageRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageResponse>> PrepareAsyncPostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageResponse>>(PrepareAsyncPostImageRequestRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ImageResponse>* AsyncPostImageRequestRaw(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ImageResponse>* PrepareAsyncPostImageRequestRaw(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::ImageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageResponse>> AsyncPostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageResponse>>(AsyncPostImageRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageResponse>> PrepareAsyncPostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageResponse>>(PrepareAsyncPostImageRequestRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::ImageResponse>* AsyncPostImageRequestRaw(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ImageResponse>* PrepareAsyncPostImageRequestRaw(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PostImageRequest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends an image to be stored
    virtual ::grpc::Status PostImageRequest(::grpc::ServerContext* context, const ::ImageRequest* request, ::ImageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PostImageRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PostImageRequest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PostImageRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PostImageRequest(::grpc::ServerContext* context, const ::ImageRequest* request, ::ImageResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPostImageRequest(::grpc::ServerContext* context, ::ImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::ImageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PostImageRequest<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_PostImageRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PostImageRequest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PostImageRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PostImageRequest(::grpc::ServerContext* context, const ::ImageRequest* request, ::ImageResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PostImageRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PostImageRequest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ImageRequest, ::ImageResponse>(std::bind(&WithStreamedUnaryMethod_PostImageRequest<BaseClass>::StreamedPostImageRequest, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PostImageRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PostImageRequest(::grpc::ServerContext* context, const ::ImageRequest* request, ::ImageResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPostImageRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ImageRequest,::ImageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PostImageRequest<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PostImageRequest<Service > StreamedService;
};


#endif  // GRPC_template_5fmatch_2eproto__INCLUDED
