// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: template_match.proto

#include "template_match.pb.h"
#include "template_match.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* ImageRecognitionRpc_method_names[] = {
  "/ImageRecognitionRpc/PostImageRequest",
};

std::unique_ptr< ImageRecognitionRpc::Stub> ImageRecognitionRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageRecognitionRpc::Stub> stub(new ImageRecognitionRpc::Stub(channel));
  return stub;
}

ImageRecognitionRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PostImageRequest_(ImageRecognitionRpc_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ImageRecognitionRpc::Stub::PostImageRequest(::grpc::ClientContext* context, const ::ImageRequest& request, ::ImageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PostImageRequest_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::ImageResponse>* ImageRecognitionRpc::Stub::AsyncPostImageRequestRaw(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ImageResponse>::Create(channel_.get(), cq, rpcmethod_PostImageRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ImageResponse>* ImageRecognitionRpc::Stub::PrepareAsyncPostImageRequestRaw(::grpc::ClientContext* context, const ::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ImageResponse>::Create(channel_.get(), cq, rpcmethod_PostImageRequest_, context, request, false);
}

ImageRecognitionRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageRecognitionRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageRecognitionRpc::Service, ::ImageRequest, ::ImageResponse>(
          std::mem_fn(&ImageRecognitionRpc::Service::PostImageRequest), this)));
}

ImageRecognitionRpc::Service::~Service() {
}

::grpc::Status ImageRecognitionRpc::Service::PostImageRequest(::grpc::ServerContext* context, const ::ImageRequest* request, ::ImageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


