// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_proto.proto

#ifndef PROTOBUF_INCLUDED_test_5fproto_2eproto
#define PROTOBUF_INCLUDED_test_5fproto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_test_5fproto_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_test_5fproto_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_test_5fproto_2eproto();
class TestProto;
class TestProtoDefaultTypeInternal;
extern TestProtoDefaultTypeInternal _TestProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::TestProto* Arena::CreateMaybeMessage<::TestProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class TestProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TestProto) */ {
 public:
  TestProto();
  virtual ~TestProto();

  TestProto(const TestProto& from);

  inline TestProto& operator=(const TestProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestProto(TestProto&& from) noexcept
    : TestProto() {
    *this = ::std::move(from);
  }

  inline TestProto& operator=(TestProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TestProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestProto* internal_default_instance() {
    return reinterpret_cast<const TestProto*>(
               &_TestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TestProto* other);
  friend void swap(TestProto& a, TestProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestProto* New() const final {
    return CreateMaybeMessage<TestProto>(nullptr);
  }

  TestProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TestProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TestProto& from);
  void MergeFrom(const TestProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool test_bool = 1;
  void clear_test_bool();
  static const int kTestBoolFieldNumber = 1;
  bool test_bool() const;
  void set_test_bool(bool value);

  // int32 test_int = 2;
  void clear_test_int();
  static const int kTestIntFieldNumber = 2;
  ::google::protobuf::int32 test_int() const;
  void set_test_int(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TestProto)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool test_bool_;
  ::google::protobuf::int32 test_int_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_test_5fproto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestProto

// bool test_bool = 1;
inline void TestProto::clear_test_bool() {
  test_bool_ = false;
}
inline bool TestProto::test_bool() const {
  // @@protoc_insertion_point(field_get:TestProto.test_bool)
  return test_bool_;
}
inline void TestProto::set_test_bool(bool value) {
  
  test_bool_ = value;
  // @@protoc_insertion_point(field_set:TestProto.test_bool)
}

// int32 test_int = 2;
inline void TestProto::clear_test_int() {
  test_int_ = 0;
}
inline ::google::protobuf::int32 TestProto::test_int() const {
  // @@protoc_insertion_point(field_get:TestProto.test_int)
  return test_int_;
}
inline void TestProto::set_test_int(::google::protobuf::int32 value) {
  
  test_int_ = value;
  // @@protoc_insertion_point(field_set:TestProto.test_int)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_test_5fproto_2eproto
