#ifndef TEXAS_HOLDEM_CALCULATOR_H_
#define TEXAS_HOLDEM_CALCULATOR_H_

namespace poker {

enum SUITED {
  SUITED,
  UNSUITED,
};

enum PlayerHand {
  SUITED_CONNECTOR,
  UNSUITED_CONNECTOR,
  UNSUITED_RAINBOW,
  SUITED_RAINBOW, // 1 GAP CARDS
  SUITED_TWO_GAP,
  UNSUITED_TWO_GAP,
  SUITED_THREE_GAP,
  UNSUITED_THREE_GAP,
  POCKET_ACES,
  POCKET_KINGS,
  POCKET_QUEENS,
  POCKET_JACKS,
  POCKET_NUMBERS,
  POCKET_TWOS, // two
  SUITED_ACE_NUMBER,
  UNSUITED_ACE_NUMBER,
  SUITED_KING_NUMBER,
  UNSUITED_KING_NUMBER,
  SUITED_JACK_NUMBER,

};

}  // namespace poker

#endif  // TEXAS_HOLDEM_CALCULATOR_H_
